# このワークフローでは、GitHub によって認定されていないアクションを使用しています。
# これらはサードパーティによって提供されており、
# 独自の利用規約、プライバシーポリシー、およびサポート
# ドキュメントの対象となります。

name: DebugBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # リポジトリのルートディレクトリを起点としたソリューションファイルのパス.
  SOLUTION_FILE_PATH: project/CakeEngine.slnx
  # Visual Studio の構成.
  CONFIGURATION: Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - name: Checkout
    - uses: actions/checkout@v6

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v3
      with:
        msbuild-architecture: x64

    - name: Build
      run: msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
